# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f18e3b4d1d8be130b73d0a8998a1eb40be0ce91e45375f75252b8a29596b2d05798d0055608bcc144da5aeeec6b21da636f1b7db781b11c6b7c61cc50b4299

test:
  secret_key_base: dd0e93a4fcc45fc30d631635f8a32708cdab840058ce783c74efd4bfe3196f266ac7ab99b09cc8f16dc5c454246e63e7045af2199465772b0657c005ecbf42a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #Mailgun through SMTP
  api_key: 'key-9f75604940380989031f758d701be4da'
  domain: 'sandbox5f290d117adb441596c5dee78e5a41ed.mailgun.org'
  username: 'postmaster@sandbox5f290d117adb441596c5dee78e5a41ed.mailgun.org'
  password: '921a0b4275bfdc7f15258aa9bf2749e8'
  gmail_username: 'm.alshenawy91'


